"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { UserNav } from "@/components/user-nav";
import { Sidebar } from "@/components/sidebar";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [isMenuOpened, setIsMenuOpened] = useState(false);
  return (
    <html lang="en">
      <body className="w-full grid grid-cols-1 md:grid-cols-8 lg:grid-cols-6">
        <Sidebar
          className={`md:col-span-2 md:static lg:col-span-1     ${
            isMenuOpened
              ? "absolute w-1/2 md:hidden  shadow-lg z-50 "
              : "hidden  md:block lg:col-span-1  md:col-span-2 "
          }`}
          setMenu={setIsMenuOpened}
        />
        <div
          className={`col-span-3 md:col-span-6 lg:col-span-5 md:border-l  ${
            isMenuOpened
              ? "md:col-span-full lg:col-span-full"
              : "md:col-span-6 lg:col-span-5"
          }`}
          // onClick={() => setIsMenuOpened((prevState) => !prevState)}
        >
          <header className="h-16 py-5   w-full justify-between flex items-center px-5 lg:px-10 border-b-[1px] dark:bg-blue-800 dark:border-none border-gray-200 ">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6 dark:fill-white fill-black"
              viewBox="0 0 24 24"
              onClick={() => setIsMenuOpened((prevState) => !prevState)}
            >
              <path d="M3 4H21V6H3V4ZM3 11H21V13H3V11ZM3 18H21V20H3V18Z"></path>
            </svg>
            <UserNav />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
