import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { UserNav } from "@/components/user-nav";
import { Sidebar } from "@/components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="w-full grid grid-cols-5 ">
        {/* <div className="w-[20%] flex  flex-col  shadow-lg h-screen sticky">
          <h1 className="text-xl h-16 font-bold px-10 py-5 border-r-[1px] dark:border-gray-900 dark:bg-blue-800 bg-slate-300">
            Walia Jobs
          </h1>
          <div className="p-10  bg-slate-200 dark:bg-blue-950 h-full">
            <ul className="flex flex-col gap-5 font-medium">
              <Link href="/" className="">
                Dashboard
              </Link>
              <Link href="/users">Users</Link>
              <Link href="/jobs">Jobs</Link>
              <Link href="/companies">Companies</Link>
              <Link href="/blogs">Blogs</Link>
              <Link href="/cvs">CVs</Link>
            </ul>
          </div>
        </div> */}
        <Sidebar className="hidden lg:block" />
        <div className="col-span-3 lg:col-span-4 lg:border-l">
          <header className="h-16 py-5 justify-between flex items-center px-10 border-b-[1px] dark:bg-blue-800 dark:border-none border-gray-200 ">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="w-6 h-6"
              viewBox="0 0 24 24"
            >
              <path d="M3 4H21V6H3V4ZM3 11H21V13H3V11ZM3 18H21V20H3V18Z"></path>
            </svg>{" "}
            {/* <div className="border-2 flex items-center justify-center rounded-full w-10 h-10 border-black">
              pro
            </div> */}
            <UserNav />
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
